In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

/bin/bash: google-drive-ocamlfuse: command not found

In [0]:
import sys
sys.path.insert(0, 'drive/')

In [0]:
!pip install -q keras
!pip install -q tensorflow
!pip install -q numpy
!pip install -q pandas
!pip install -q nltk
!pip install -U -q PyDrive
!pip install -U -q sumeval

     |████████████████████████████████| 993kB 33.3MB/s
  Building wheel for PyDrive (setup.py) ... done
     |████████████████████████████████| 51kB 15.9MB/s
  Building wheel for sumeval (setup.py) ... done
  Building wheel for sacrebleu (setup.py) ... done

In [0]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# 2. Load a file by ID and create local file.
downloaded = drive.CreateFile({'id':'1RZ7L1ToT_f5cj73U26Dbi7sIm2V4xznF'}) # replace fileid with Id of file you want to access
downloaded.GetContentFile('wikihowAll.csv') # now you can use export.csv 

downloaded2 = drive.CreateFile({'id':'1_M0ya_yrrNwTEEPXjXycDM73KM8CR1Ln'}) # replace fileid with Id of file you want to access
downloaded2.GetContentFile('glove.6B.100d.txt') # now you can use export.csv

In [0]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os as os
import re
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [0]:
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Input,Dense,GRU,Embedding,CuDNNGRU,CuDNNLSTM
from tensorflow.python.keras.optimizers import RMSprop
from tensorflow.python.keras.callbacks import ModelCheckpoint
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from sumeval.metrics.rouge import RougeCalculator
from nltk.translate.bleu_score import sentence_bleu

In [0]:
wikiHow = pd.read_csv("wikihowAll.csv")
#news

In [0]:
wikiHow.shape

(215365, 3)

In [0]:
wikiHow.head()

                                            headline  ...                                               text
0  \nKeep related supplies in the same area.,\nMa...  ...   If you're a photographer, keep all the necess...
1  \nCreate a sketch in the NeoPopRealist manner ...  ...   See the image for how this drawing develops s...
2  \nGet a bachelor’s degree.,\nEnroll in a studi...  ...   It is possible to become a VFX artist without...
3  \nStart with some experience or interest in ar...  ...   The best art investors do their research on t...
4  \nKeep your reference materials, sketches, art...  ...   As you start planning for a project or work, ...

[5 rows x 3 columns]

In [0]:
wikiHow.isnull().sum()

headline     818
title          1
text        1071
dtype: int64

In [0]:
wikiHow = wikiHow.dropna()
wikiHow = wikiHow.drop(['title'], 1)
wikiHow['text']=wikiHow['text'].fillna("")
wikiHow['headline']=wikiHow['headline'].fillna("")
wikiHow = wikiHow.reset_index(drop=True)

In [0]:
wikiHow.tail()

                                                 headline                                               text
214289  \nConsider changing the spelling of your name....   If you have a name that you like, you might f...
214290  \nTry out your name.,\nDon’t legally change yo...   Your name might sound great to you when you s...
214291  \nUnderstand the process of relief printing.,\...   Relief printing is the oldest and most tradit...
214292  \nUnderstand the process of intaglio printing....   Intaglio is Italian for "incis­ing," and corr...
214293  \nUnderstand the different varieties of lithog...   Lithography is a big term often used to refer...

In [0]:
wikiHow.text[15]

' Whether you are teaching a skill, delivering information or increasing awareness, outline the goals of your workshop. What do you want your workshop participants to learn? This analysis may result in a list of specific skills you will be teaching, concrete topics you will cover, or simply a feeling you will inspire in your participants. Think carefully about what you want to accomplish and why it is important.Some examples of workshop objectives include:\n\n\nLearn how to write a persuasive cover letter.\nLearn how to break bad news to a patient.\nLearn 5 techniques to get a reluctant student to talk in class.\nLearn how to create an effective Powerpoint presentation.;\n, Will the workshop participants know one another or are they strangers? Will they come in with knowledge about your topic or will they be completely unfamiliar with it? Are they choosing to attend your workshop or is it a requirement for their job training? Answers to all of these questions will affect how you organize your workshop.For example, if your audience already knows each other, you might be able to launch into group activities very quickly. If they are complete strangers, you might need to schedule extra time for icebreakers and introductions.\n\n, These are the times when participants are most awake and alert.\n\nYou want your participants to be fully engaged and aware. If you can, avoid scheduling evening workshops after the workday when everyone is tired and impatient., Pass around flyers, hang up posters, or contact suitable businesses to encourage workshop participation. Having a catchy title helps, as does a brief explanation for why your workshop is important and necessary.Be sure to include images as well as text in your flyers to catch people\'s attention.\n\n, A workshop is not the same as a large lecture. You want your group to be small enough to ask all their questions, practice their skills, and work together. But you also want your workshop to be large enough to keep things interesting. Ideally a workshop will have 8-15 participants.Sometimes you don\'t have a choice about your group size. If you have a very large group, find creative ways to make sure the size doesn\'t become overwhelming. For example, a group of 40 participants could be divided into 5 different break-out groups of 8 participants each. You could also bring in co-facilitators and co-presenters to handle groups that are larger than ideal.\n\n, Some workshops require that participants do work well before the workshop takes place. Perhaps they have to study journal articles, write a short story, or read one another\'s work. If your participants have homework to do before the workshop takes place, be sure that your expectations are clearly stated from the beginning.\n\n\nBe sure to set hard deadlines if your students have to submit work to the group ahead of time. Be clear about where and how your students should submit their work. Will they have to give you hard copies, or will you circulate materials by email?\n\n, Most workshops are time-limited. They can be as short as 30 minutes or as long as three days. But no matter what, you will only have a short period of time to impart your knowledge to participants.Rather than covering absolutely everything in a short amount of time, think about the most important skills, techniques, and information you want your audience to gain. Prioritize those in your lesson plan.\n\n, Adults learn in all kinds of ways: visually, orally, through hands-on practice, or any combination of the above.Remember that you might not know your participants\' learning styles ahead of time, so you will want to have a variety of materials prepared. Depending on the topic and objective of your workshop, you might want to prepare paper handouts, audio-visual aids, computer-based lesson plans, and role-playing activities., Readings, case studies, lists of key terms, and quizzes are all possible teaching aids you might wish to prepare. It is best if you prepare these handouts well ahead of time. That way you can catch typos or errors. Be sure to use a large, easy-to-read font. Give each document a clear label and date so that your participants will be able to use these handouts in the future.\n\n\nIf you have lengthy readings, consider precirculating these handouts to the group so that they can come in prepared.If you are handing out numerous documents, consider providing your participants with a folder or binder to keep their papers neat and organized. If you give this workshop often enough, you might even want to compile your materials into a bound book that you give to your attendees.\n\n, If you plan to present a slideshow, video clips, or sound clips, you will have to prepare these ahead of time. Test them at home to make sure they are working correctly. Make sure that they are in a format that can be used in your workshop space.\n\n\nIt is wise to consult with your venue\'s a/v technicians to make sure that your materials can be presented properly. Not all projectors are compatible with Macintosh computers, for example. And some rooms might not have sound projection. Make sure that your venue can accommodate whatever technology you wish to use.\n\n, If your workshop participants will be expected to complete a computerized quiz or participate in an online discussion forum, you will need to organize these materials ahead of time.Think about whether your participants will have to bring in their own personal computers or devices, and notify them if so.\n\n\nIf your participants will be expected to do activities online, be sure to consult with your venue\'s a/v technician. You will have to make sure that your workshop space is equipped with wireless internet, and you might have to ask for the network\'s password in advance.\n\n, Depending on the topic and size of your workshop, you might want to bring in other team members to facilitate learning. An expert can provide a live demonstration of a new medical technique; a guest speaker might be able to tell a lively anecdote about why your workshop topic is important; and an assistant might be able to help you manage a large group. If you require help from anyone, make sure that you recruit them well ahead of time. The more prepared they are, the better your workshop will be.\n\n, Interaction amongst a group of participants sets a workshop apart from other ways of learning. Brainstorm educational group activities that are suitable to your workshop\'s objectives. Keep in mind that activities can be done in pairs, small groups, or as a full group. Make sure that you include enough opportunities for every workshop participant to contribute meaningfully to your workshop. Some possible group activities include:\n\n\nDebates. Break the workshop into two groups and have each group argue for their position.\nThink-pair-shares. Ask your participants a discussion question. Have them think about it on their own, discuss their thoughts with a partner, and then share their conclusions with the full group.\nQuestion-and-answer sessions. If you have a lot of information to present, include your attendees in the discussion by allowing them to ask questions about the material. You can answer these questions yourself or ask other workshop participants to answer them.\nRole-playing activities. Assign participants roles to play in order to practice the new techniques they are learning.\nBrainstorming sessions. Ask your workshop to shout out as many ideas as they can think of. Write them all down on a chalkboard or whiteboard. Then ask your workshop to evaluate what they have come up with.\n\n, People are more focused on tasks when they have the chance to take short breaks.They are also more likely to remember what they have learned. Schedule your workshop plan to include at least one 5-minute break per hour of your workshop. This will shorten your time with your participants but will make that time more valuable.\n\n, Actual activities can often take 10-20% more time than we estimate.If you think a q-and-a session will last 10 minutes, it might very well last 12 minutes or longer. Build in enough time for each major activity or topic you want to cover. Resist the urge to cram in as much as possible: your participants will feel tired and rushed.\n\n\nIf you are worried that your workshop will end early, you can always prepare a couple of optional extra activities that will reinforce learning. If you have time for them, great! And if not, no harm done.\n\n, Workshops take a lot of work and energy. Help keep your participants\' energy levels up by providing healthy foods and beverages.Ideally the costs of these snacks will be covered through participant registration fees or by the organization that asked you to lead the workshop. You should not have to pay for snacks out-of-pocket.\n\n\nTry to avoid junk foods. Unhealthy foods might give short bursts of energy but then will cause energy crashes very soon. That will leave your participants bored and tired. Aim for energizing healthy snacks such as fruit, vegetables, hummus, and whole grain breads., Leave yourself plenty of time to set up the space and get comfortable in the room. You might have to meet with a/v technicians, caterers, or your team members before your workshop begins as well. Give yourself as much time as you can in case you have to troubleshoot or make last-minute adjustments to your workshop plan., Computers, laptops, projectors, and speakers will all have to be fine-tuned in advance. After all, you want your workshop time to be productive: you do not want to spend it fiddling with technology. If you can, see if you can have the venue\'s a/v technician assist you with the set-up. You might not be familiar with the room\'s technological capabilities, and an expert might be able to set everything up more efficiently.\n\n, The way you arrange the chairs will depend on the size of your group, the size of the room, and the activities you have planned. Ideally the group will be small enough to sit in a circle or semi-circle: this will help establish rapport and facilitate conversation.If everyone will need to look at the front to watch video clips or a live demo, perhaps a semi-circle or straight rows of seats is more appropriate., If you have notebooks or other workshop materials to hand out, place them on the tables or chairs in advance to save time during the workshop. Make sure they are in the correct order and that they are clearly labeled. Other materials you might need to set up in your workshop space include:\n\n\nSnacks and beverages.\nName-tags and markers.\nPens and pencils.\n\n, Arriving early allows you to set up, relax and get to know participants before the start of the workshop. This helps in building relationships with the participants.\n\n, Once everyone is seated, you will have to orient them to your workshop. Be sure to tell them your name and what they should call you. Give a few words about why you should be considered an expert in the topic and what got you interested in it. Explain to your participants what the goal of the workshop is and why it is important. It is also a good idea to give a rough outline of how the workshop will be run so that they can be prepared. Try to limit this segment to just a couple of minutes.\n\n\nEven if your topic is a serious one, consider using humor to lighten the mood and get everyone comfortable with one another.\nExplain to your participants what the materials around the room are and what they should do with them. For example, you can ask people to fill out name-tags, grab a cup of coffee, and make sure they have their handouts. If you would rather that your participants not pull out their readings or laptops right away, you can tell them when those materials will be needed.\n\n, Ask your participants to introduce themselves. Limit the introductions to a few sentences by asking everyone to answer two or three specific questions, such as their names and what they hope to gain from the workshop. You don\'t want the icebreakers to go on forever, but it is important that your attendees feel comfortable talking in front of the group.\n\n\nYou can also ask everybody to break the ice by answering a light-hearted question like "What is your favorite movie?" or "What is your favorite bad song?"\n\n, This is when all of your careful preparations can be put into action. Have your outline in front of you, and try to stick to the outline if you can. Feel free to tell your participants directly what you are doing and why. Your lesson plan doesn\'t have to be a surprise, and your participants might appreciate being told why you\'ve organized the workshop in the way that you did. For example, you might tell them:\n\n\n"First we are going to go over our case studies to make sure we understand their nuances. After that, we will divide into small groups to determine an ideal solution to the problem."\n"We\'re going to spend some time learning key terms that will be useful to you as you learn this new computer program. After I explain these terms, we\'ll take a quiz to make sure we are on the same page. After that, we will open things up for discussion."\n"Please introduce yourself to the person sitting next to you. In a few minutes, you will role-play a counselor-student interaction with your partner."\n\n, It is good to have a plan for your workshop, but be prepared to alter your workshop\'s content based on the reactions and experiences of the participants. Build some flex time into your lesson plan so that you can address their questions, concerns, and interests.You can even provide options for activities that your workshop group can vote on. This will allow you to focus on what really matters and skip over redundant or unnecessary content.\n\n, Always follow up the delivery of information with the reinforcement of that information through some kind of group activity. Interactive group work is a particularly effective method to teach problem-solving techniques.\n\nA workshop is not the same thing as a lecture, and you want to honor the thoughts and opinions of your workshop participants. Let them teach each other at the same time that you are teaching them. For example, you can:\n\nDeliver information in short spurts and then allow participants to ask questions.\nDivide participants into groups to complete a task and ask them to report back to the entire group.\nShow a video clip and then ask pairs of participants to discuss their reactions.\nProvide advice about how to handle a difficult situation and then ask small groups of participants to role-play the scenario.\nHave an expert demonstrate a technique and then ask your students to take a collaborative quiz about the technique.\n\n, You do not want to micromanage every stage of the workshop. Your participants might get bored or annoyed.Keep in mind that a workshop is different from a lecture or a typical meeting: it is a format that thrives on interaction, activity, and group work., Scheduling breaks helps people assimilate the information and reflect. Let participants know how often they will get breaks and the lengths of the breaks. This allows workshop attendees to plan accordingly for restroom usage, phone calls and other personal needs. Do not skip breaks, even if you are running short on time.\n\n, Attention spans begin to wane after 20 minutes of the same activity. View this fact as an opportunity for creativity instead of as a problem. Change up your activities, ask your participants to rearrange their chairs, or schedule a break at least once every 20-30 minutes to keep everyone engaged and motivated., Even if you are treating a serious topic, humor can be a great way to emphasize information and keep everyone attentive.Think about ways that you can introduce humor in a responsible, ethical way into your presentations, discussions, and activities. This will also encourage your participants to remain relaxed, alert, and comfortable.\n\n, Make sure that all of your workshop participants are treated equally and respectfully.This means that any leadership roles (such as group discussion leader) should be distributed evenly across the workshop. Encourage quiet, shy participants to speak. You want everyone to feel heard and respected. Similarly, you do not want a single participant\'s voice (or your own voice for that matter) to dominate the discussion.\n\n, Most workshops will run smoothly. After all, the participants presumably want to be there and want to learn. However, there might be scenarios where somebody is unwilling to participate or might be insulting to a colleague. Be professional no matter what, and encourage respectful behavior by modeling respectful behavior.Be clear in what you expect from your participants. If you have a participant who is acting up or trying to bully a colleague, consider speaking privately with that person. Emphasize the importance of what you are teaching, and tell them that you expect adult, professional behavior from them.\n\n, Explain everything that your participants have learned over the course of the session.This will help emphasize how far they have come and what new skills they have acquired. Refer explicitly to the objectives you laid out at the beginning of the workshop, and explain how you think the participants have met those objectives. Congratulate your workshop for their hard work and for their new knowledge.\n\n, Design an evaluation form that your participants can fill out in the last few minutes of the workshop. Be sure that you leave them with enough time to comment and consider your questions carefully.Immediate feedback not only will help you improve your workshop but will also help reinforce the learning your participants have undertaken.Good questions to ask include:\n\nWhat is the stated objective of this workshop? Did the workshop meet its stated objective?\nWhat activities helped your learning the most? The least?\nWas the workshop an appropriate length?\nWhat workshop materials (handouts, readings, quizzes, etc.) were the most useful? Which ones were the least useful?\nHow have you learned or grown from this workshop?\nHow do you think your colleagues have learned or grown?\nHow would you change this workshop in the future? Any suggestions for improvements?\nAre there any topics that you would like to take a workshop on?\n\n, Ask workshop attendees if you may contact them in the future for their input. Some people need time to reflect back on their workshop experiences. Following up with workshop participants several days or weeks later might reveal new insights. You can ask additional questions such as:\n\n\nHow well have you retained the information you learned in the workshop?\nDo you still find yourself thinking about the workshop?\nHow has the workshop helped you at work? Were there ways it could have helped you more?\nWhat materials have you found useful since the workshop? What materials have you thrown away or forgotten about?\n\n, If enough participants are interested in more advanced versions of your workshop, consider scheduling a Part 2. In the follow-up workshop, you can address more of their questions, dig more deeply into the topic, or engage in more advanced versions of the techniques taught in Part 1. Be sure that your follow-up workshop is not too repetitive and that it is suitable for more advanced attendees.\n\n'

In [0]:
wikiHow.headline[15]

"\nDefine the workshop objective.,\nDecide who your audience is.,\nSchedule your workshop for the morning or early afternoon.,\nPublicize your workshop.,\nRecruit 8-15 participants for your workshop.,\nPrepare your participants for the workshop.,\nPrioritize your goals for the workshop.,\nPrepare a variety of teaching aids.,\nPrepare paper handouts.,\nArrange your audio-visual materials.,\nOrganize your computer-based materials.,\nRecruit experts, speakers, and assistants.,\nDecide on your group activities.,\nLeave time for breaks.,\nResist cramming.,\nSecure catering.,\nArrive early.,\nSet up all equipment before participants arrive.,\nArrange the chairs in advance.,\nDistribute materials.,\nGreet participants as they arrive.,\nIntroduce yourself and the workshop.,\nBegin icebreakers.,\nExecute your lesson plan.,\nBe flexible.,\nUse interactive exercises to reinforce information.,\nDon't talk too much.,\nStick to your scheduled breaks.,\nSwitch up activities every 20-30 minutes.,\nLighten the mood.,\nMaintain a respectful, democratic atmosphere.,\nBe prepared for the unexpected.,\nConclude the workshop with a summary of what they have learned.,\nGet feedback immediately after the session.,\nFollow up with the participants a few days or weeks later.,\nSchedule a follow-up workshop if necessary."

In [0]:
contractions = { 
"ain't": "am not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he's": "he is",
"how'd": "how did",
"how'll": "how will",
"how's": "how is",
"i'd": "i would",
"i'll": "i will",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'll": "it will",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"must've": "must have",
"mustn't": "must not",
"needn't": "need not",
"oughtn't": "ought not",
"shan't": "shall not",
"sha'n't": "shall not",
"she'd": "she would",
"she'll": "she will",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"that'd": "that would",
"that's": "that is",
"there'd": "there had",
"there's": "there is",
"they'd": "they would",
"they'll": "they will",
"they're": "they are",
"they've": "they have",
"wasn't": "was not",
"we'd": "we would",
"we'll": "we will",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"where'd": "where did",
"where's": "where is",
"who'll": "who will",
"who's": "who is",
"won't": "will not",
"wouldn't": "would not",
"you'd": "you would",
"you'll": "you will",
"you're": "you are"
}

In [0]:
def clean_text(text,contradictions = True):
    # Convert words to lower case
    
    if type(text) is str:
        text = text.lower()
    
    # Replace contractions with their longer forms 
    if contradictions:
        text = text.split()
        new_text = []
        for word in text:
            if word in contractions:
                new_text.append(contractions[word])
            else:
                new_text.append(word)
        text = " ".join(new_text)
    
    # Format words and remove unwanted characters
    text = re.sub(r'\<a href', ' ', text)
    text = re.sub(r'https?:\/\/.*[\r\n]*', '', text, flags=re.MULTILINE)
    text = re.sub(r'&amp;', '', text) 
    #text = re.sub(r'[_"\-;%()|+&=*%.,!?:#$@\[\]/]', ' ', text)
    text = re.sub(r'<br\s*\/?>', '', text)
    text = re.sub(r'<br />', ' ', text)
    text = re.sub(r'[^-''.,;<>\\|+!?"-*_a-zA-Z0-9 \n\.]', ' ', text)
    
    #text = re.sub(r'\'', ' ', text)

    return text

In [0]:
clean_summaries = []

for summary in wikiHow.headline:
    clean_summaries.append(clean_text(summary,contradictions = True))
print("Summaries are complete.")

Summaries are complete.

In [0]:
clean_texts = []
for text in wikiHow.text:
    clean_texts.append(clean_text(text,contradictions = True))
print("Texts are complete.")

Texts are complete.

In [0]:
clean_texts[15]

'whether you are teaching a skill, delivering information or increasing awareness, outline the goals of your workshop. what do you want your workshop participants to learn? this analysis may result in a list of specific skills you will be teaching, concrete topics you will cover, or simply a feeling you will inspire in your participants. think carefully about what you want to accomplish and why it is important.some examples of workshop objectives include  learn how to write a persuasive cover letter. learn how to break bad news to a patient. learn 5 techniques to get a reluctant student to talk in class. learn how to create an effective powerpoint presentation.; , will the workshop participants know one another or are they strangers? will they come in with knowledge about your topic or will they be completely unfamiliar with it? are they choosing to attend your workshop or is it a requirement for their job training? answers to all of these questions will affect how you organize your workshop.for example, if your audience already knows each other, you might be able to launch into group activities very quickly. if they are complete strangers, you might need to schedule extra time for icebreakers and introductions. , these are the times when participants are most awake and alert. you want your participants to be fully engaged and aware. if you can, avoid scheduling evening workshops after the workday when everyone is tired and impatient., pass around flyers, hang up posters, or contact suitable businesses to encourage workshop participation. having a catchy title helps, as does a brief explanation for why your workshop is important and necessary.be sure to include images as well as text in your flyers to catch people\'s attention. , a workshop is not the same as a large lecture. you want your group to be small enough to ask all their questions, practice their skills, and work together. but you also want your workshop to be large enough to keep things interesting. ideally a workshop will have 8-15 participants.sometimes you do not have a choice about your group size. if you have a very large group, find creative ways to make sure the size does not become overwhelming. for example, a group of 40 participants could be divided into 5 different break-out groups of 8 participants each. you could also bring in co-facilitators and co-presenters to handle groups that are larger than ideal. , some workshops require that participants do work well before the workshop takes place. perhaps they have to study journal articles, write a short story, or read one another\'s work. if your participants have homework to do before the workshop takes place, be sure that your expectations are clearly stated from the beginning. be sure to set hard deadlines if your students have to submit work to the group ahead of time. be clear about where and how your students should submit their work. will they have to give you hard copies, or will you circulate materials by email? , most workshops are time-limited. they can be as short as 30 minutes or as long as three days. but no matter what, you will only have a short period of time to impart your knowledge to participants.rather than covering absolutely everything in a short amount of time, think about the most important skills, techniques, and information you want your audience to gain. prioritize those in your lesson plan. , adults learn in all kinds of ways  visually, orally, through hands-on practice, or any combination of the above.remember that you might not know your participants\' learning styles ahead of time, so you will want to have a variety of materials prepared. depending on the topic and objective of your workshop, you might want to prepare paper handouts, audio-visual aids, computer-based lesson plans, and role-playing activities., readings, case studies, lists of key terms, and quizzes are all possible teaching aids you might wish to prepare. it is best if you prepare these handouts well ahead of time. that way you can catch typos or errors. be sure to use a large, easy-to-read font. give each document a clear label and date so that your participants will be able to use these handouts in the future. if you have lengthy readings, consider precirculating these handouts to the group so that they can come in prepared.if you are handing out numerous documents, consider providing your participants with a folder or binder to keep their papers neat and organized. if you give this workshop often enough, you might even want to compile your materials into a bound book that you give to your attendees. , if you plan to present a slideshow, video clips, or sound clips, you will have to prepare these ahead of time. test them at home to make sure they are working correctly. make sure that they are in a format that can be used in your workshop space. it is wise to consult with your venue\'s a v technicians to make sure that your materials can be presented properly. not all projectors are compatible with macintosh computers, for example. and some rooms might not have sound projection. make sure that your venue can accommodate whatever technology you wish to use. , if your workshop participants will be expected to complete a computerized quiz or participate in an online discussion forum, you will need to organize these materials ahead of time.think about whether your participants will have to bring in their own personal computers or devices, and notify them if so. if your participants will be expected to do activities online, be sure to consult with your venue\'s a v technician. you will have to make sure that your workshop space is equipped with wireless internet, and you might have to ask for the network\'s password in advance. , depending on the topic and size of your workshop, you might want to bring in other team members to facilitate learning. an expert can provide a live demonstration of a new medical technique; a guest speaker might be able to tell a lively anecdote about why your workshop topic is important; and an assistant might be able to help you manage a large group. if you require help from anyone, make sure that you recruit them well ahead of time. the more prepared they are, the better your workshop will be. , interaction amongst a group of participants sets a workshop apart from other ways of learning. brainstorm educational group activities that are suitable to your workshop\'s objectives. keep in mind that activities can be done in pairs, small groups, or as a full group. make sure that you include enough opportunities for every workshop participant to contribute meaningfully to your workshop. some possible group activities include  debates. break the workshop into two groups and have each group argue for their position. think-pair-shares. ask your participants a discussion question. have them think about it on their own, discuss their thoughts with a partner, and then share their conclusions with the full group. question-and-answer sessions. if you have a lot of information to present, include your attendees in the discussion by allowing them to ask questions about the material. you can answer these questions yourself or ask other workshop participants to answer them. role-playing activities. assign participants roles to play in order to practice the new techniques they are learning. brainstorming sessions. ask your workshop to shout out as many ideas as they can think of. write them all down on a chalkboard or whiteboard. then ask your workshop to evaluate what they have come up with. , people are more focused on tasks when they have the chance to take short breaks.they are also more likely to remember what they have learned. schedule your workshop plan to include at least one 5-minute break per hour of your workshop. this will shorten your time with your participants but will make that time more valuable. , actual activities can often take 10-20% more time than we estimate.if you think a q-and-a session will last 10 minutes, it might very well last 12 minutes or longer. build in enough time for each major activity or topic you want to cover. resist the urge to cram in as much as possible  your participants will feel tired and rushed. if you are worried that your workshop will end early, you can always prepare a couple of optional extra activities that will reinforce learning. if you have time for them, great! and if not, no harm done. , workshops take a lot of work and energy. help keep your participants\' energy levels up by providing healthy foods and beverages.ideally the costs of these snacks will be covered through participant registration fees or by the organization that asked you to lead the workshop. you should not have to pay for snacks out-of-pocket. try to avoid junk foods. unhealthy foods might give short bursts of energy but then will cause energy crashes very soon. that will leave your participants bored and tired. aim for energizing healthy snacks such as fruit, vegetables, hummus, and whole grain breads., leave yourself plenty of time to set up the space and get comfortable in the room. you might have to meet with a v technicians, caterers, or your team members before your workshop begins as well. give yourself as much time as you can in case you have to troubleshoot or make last-minute adjustments to your workshop plan., computers, laptops, projectors, and speakers will all have to be fine-tuned in advance. after all, you want your workshop time to be productive  you do not want to spend it fiddling with technology. if you can, see if you can have the venue\'s a v technician assist you with the set-up. you might not be familiar with the room\'s technological capabilities, and an expert might be able to set everything up more efficiently. , the way you arrange the chairs will depend on the size of your group, the size of the room, and the activities you have planned. ideally the group will be small enough to sit in a circle or semi-circle  this will help establish rapport and facilitate conversation.if everyone will need to look at the front to watch video clips or a live demo, perhaps a semi-circle or straight rows of seats is more appropriate., if you have notebooks or other workshop materials to hand out, place them on the tables or chairs in advance to save time during the workshop. make sure they are in the correct order and that they are clearly labeled. other materials you might need to set up in your workshop space include  snacks and beverages. name-tags and markers. pens and pencils. , arriving early allows you to set up, relax and get to know participants before the start of the workshop. this helps in building relationships with the participants. , once everyone is seated, you will have to orient them to your workshop. be sure to tell them your name and what they should call you. give a few words about why you should be considered an expert in the topic and what got you interested in it. explain to your participants what the goal of the workshop is and why it is important. it is also a good idea to give a rough outline of how the workshop will be run so that they can be prepared. try to limit this segment to just a couple of minutes. even if your topic is a serious one, consider using humor to lighten the mood and get everyone comfortable with one another. explain to your participants what the materials around the room are and what they should do with them. for example, you can ask people to fill out name-tags, grab a cup of coffee, and make sure they have their handouts. if you would rather that your participants not pull out their readings or laptops right away, you can tell them when those materials will be needed. , ask your participants to introduce themselves. limit the introductions to a few sentences by asking everyone to answer two or three specific questions, such as their names and what they hope to gain from the workshop. you do not want the icebreakers to go on forever, but it is important that your attendees feel comfortable talking in front of the group. you can also ask everybody to break the ice by answering a light-hearted question like "what is your favorite movie?" or "what is your favorite bad song?" , this is when all of your careful preparations can be put into action. have your outline in front of you, and try to stick to the outline if you can. feel free to tell your participants directly what you are doing and why. your lesson plan does not have to be a surprise, and your participants might appreciate being told why you\'ve organized the workshop in the way that you did. for example, you might tell them  "first we are going to go over our case studies to make sure we understand their nuances. after that, we will divide into small groups to determine an ideal solution to the problem." "we\'re going to spend some time learning key terms that will be useful to you as you learn this new computer program. after i explain these terms, we will take a quiz to make sure we are on the same page. after that, we will open things up for discussion." "please introduce yourself to the person sitting next to you. in a few minutes, you will role-play a counselor-student interaction with your partner." , it is good to have a plan for your workshop, but be prepared to alter your workshop\'s content based on the reactions and experiences of the participants. build some flex time into your lesson plan so that you can address their questions, concerns, and interests.you can even provide options for activities that your workshop group can vote on. this will allow you to focus on what really matters and skip over redundant or unnecessary content. , always follow up the delivery of information with the reinforcement of that information through some kind of group activity. interactive group work is a particularly effective method to teach problem-solving techniques. a workshop is not the same thing as a lecture, and you want to honor the thoughts and opinions of your workshop participants. let them teach each other at the same time that you are teaching them. for example, you can  deliver information in short spurts and then allow participants to ask questions. divide participants into groups to complete a task and ask them to report back to the entire group. show a video clip and then ask pairs of participants to discuss their reactions. provide advice about how to handle a difficult situation and then ask small groups of participants to role-play the scenario. have an expert demonstrate a technique and then ask your students to take a collaborative quiz about the technique. , you do not want to micromanage every stage of the workshop. your participants might get bored or annoyed.keep in mind that a workshop is different from a lecture or a typical meeting  it is a format that thrives on interaction, activity, and group work., scheduling breaks helps people assimilate the information and reflect. let participants know how often they will get breaks and the lengths of the breaks. this allows workshop attendees to plan accordingly for restroom usage, phone calls and other personal needs. do not skip breaks, even if you are running short on time. , attention spans begin to wane after 20 minutes of the same activity. view this fact as an opportunity for creativity instead of as a problem. change up your activities, ask your participants to rearrange their chairs, or schedule a break at least once every 20-30 minutes to keep everyone engaged and motivated., even if you are treating a serious topic, humor can be a great way to emphasize information and keep everyone attentive.think about ways that you can introduce humor in a responsible, ethical way into your presentations, discussions, and activities. this will also encourage your participants to remain relaxed, alert, and comfortable. , make sure that all of your workshop participants are treated equally and respectfully.this means that any leadership roles (such as group discussion leader) should be distributed evenly across the workshop. encourage quiet, shy participants to speak. you want everyone to feel heard and respected. similarly, you do not want a single participant\'s voice (or your own voice for that matter) to dominate the discussion. , most workshops will run smoothly. after all, the participants presumably want to be there and want to learn. however, there might be scenarios where somebody is unwilling to participate or might be insulting to a colleague. be professional no matter what, and encourage respectful behavior by modeling respectful behavior.be clear in what you expect from your participants. if you have a participant who is acting up or trying to bully a colleague, consider speaking privately with that person. emphasize the importance of what you are teaching, and tell them that you expect adult, professional behavior from them. , explain everything that your participants have learned over the course of the session.this will help emphasize how far they have come and what new skills they have acquired. refer explicitly to the objectives you laid out at the beginning of the workshop, and explain how you think the participants have met those objectives. congratulate your workshop for their hard work and for their new knowledge. , design an evaluation form that your participants can fill out in the last few minutes of the workshop. be sure that you leave them with enough time to comment and consider your questions carefully.immediate feedback not only will help you improve your workshop but will also help reinforce the learning your participants have undertaken.good questions to ask include  what is the stated objective of this workshop? did the workshop meet its stated objective? what activities helped your learning the most? the least? was the workshop an appropriate length? what workshop materials (handouts, readings, quizzes, etc.) were the most useful? which ones were the least useful? how have you learned or grown from this workshop? how do you think your colleagues have learned or grown? how would you change this workshop in the future? any suggestions for improvements? are there any topics that you would like to take a workshop on? , ask workshop attendees if you may contact them in the future for their input. some people need time to reflect back on their workshop experiences. following up with workshop participants several days or weeks later might reveal new insights. you can ask additional questions such as  how well have you retained the information you learned in the workshop? do you still find yourself thinking about the workshop? how has the workshop helped you at work? were there ways it could have helped you more? what materials have you found useful since the workshop? what materials have you thrown away or forgotten about? , if enough participants are interested in more advanced versions of your workshop, consider scheduling a part 2. in the follow-up workshop, you can address more of their questions, dig more deeply into the topic, or engage in more advanced versions of the techniques taught in part 1. be sure that your follow-up workshop is not too repetitive and that it is suitable for more advanced attendees.'

In [0]:
clean_summaries[15]

'define the workshop objective., decide who your audience is., schedule your workshop for the morning or early afternoon., publicize your workshop., recruit 8-15 participants for your workshop., prepare your participants for the workshop., prioritize your goals for the workshop., prepare a variety of teaching aids., prepare paper handouts., arrange your audio-visual materials., organize your computer-based materials., recruit experts, speakers, and assistants., decide on your group activities., leave time for breaks., resist cramming., secure catering., arrive early., set up all equipment before participants arrive., arrange the chairs in advance., distribute materials., greet participants as they arrive., introduce yourself and the workshop., begin icebreakers., execute your lesson plan., be flexible., use interactive exercises to reinforce information., do not talk too much., stick to your scheduled breaks., switch up activities every 20-30 minutes., lighten the mood., maintain a respectful, democratic atmosphere., be prepared for the unexpected., conclude the workshop with a summary of what they have learned., get feedback immediately after the session., follow up with the participants a few days or weeks later., schedule a follow-up workshop if necessary.'

In [0]:
mark_start = 'ssstarttoken '  #kelime haznesi içinde bulunmayan bir başlangıç tokeni veriyoruz.
#dekoder bu tokeni gördüğü zaman kelime üretmeye başlayacak.
mark_end = ' eeendtoken' #cümle bitiş tokeni dekoder cümlenin bitmesi karar verdiği zaman bu tokeni kullanacak
data_src = []
data_dest = []

data_src = clean_texts
for line in clean_summaries:
    data_dest.append(mark_start+line+mark_end)

In [0]:
print(data_src[100])
print(data_dest[100])

it can be any color, and any type, as long as it could not potentially harm your guinea pig. set it in the area you will be training in. be sure to turn it upside-down, so that your guinea pig will not knock it over as you begin to teach the trick. a garbage can that may have contained anything that could be harmful should not be used. , gently lift them out of their cage and set them down near the garbage can other object. allow the guinea pig to sniff around if they feel the need. some may ignore it, but this does not mean that they will not do the trick-have patience. , hold out one of the treats and lure your guinea pig towards the garbage can. move it slightly, further away and around it, until your guinea pig has completed a quarter of the circle. click and treat. do this three or four times, until your guinea pig becomes comfortable with moving around it a bit. , every time the guinea pig moves forward a few steps, reward them with a click(or verbal marker) and a treat. gradually increase the amount of steps they take before receiving the treat. hopefully, your guinea pig will soon discover that moving around the garbage can does not go without rewards. many will figure this out within a few minutes of doing that same thing, but if they don't, go back to luring and go on from there as many times as your guinea pig needs it. , some guinea pigs will pick this up faster than others, and that is okay. no piggy is perfect, no matter how intelligent they may be. , the hand motion can be whatever you see fit, but i have found that holding a finger above the object, where the guinea pig can clearly see it, and moving it around in a circular motion. saying the command "around!" or "spin!" may help as well, but verbal commands are more for the trainer than for the animal themselves. from this point on, only treat your guinea pig when they walk around after your hand motion. if they do it without your motion, just sit patiently until they are done and ask them to do it afterwards. if they do it, treat and praise them immensely. it takes many guinea pigs a long time to understand this, but, if the trainer is persistent, it will be very rewarding in the end. , once the guinea pig is very good at walking around the garbage can on your hand motion, put the can up somewhere and do the motion. this can be very easy, or very hard, depending on the piggy.
ssstarttoken get a small garbage can or round, cylinder-shaped object of some sort., place your guinea pig in the general area., use a treat to lure your guinea pig to it., stand back and see if the guinea pig will try to go around on its own., eventually, begin only treating your guinea pig when they make a full circle around the object., begin enforcing a hand motion., take the garbage can away gradually. eeendtoken

In [0]:
#len(data_src)
class TokenizerWrap(Tokenizer): #tokenizer nesnesini alıyoruz.
    def __init__(self,texts,padding,reverse=False,num_words=None):
        Tokenizer.__init__(self,num_words=num_words)
        
        self.fit_on_texts(texts) #tokenizera textlerimizi veriyoruz.
        self.index_to_word = dict(zip(self.word_index.values(),self.word_index.keys())) #kelime haznesindeki kelime rakam değerlerini key value olarak
        #yer değiştirir.
        self.tokens = self.texts_to_sequences(texts) #cümleler tokenlara çevrilir.
        
        if reverse:
            self.tokens = [list(reversed(x)) for x in self.tokens] #encodera vereceğimiz tüm inputlar aynı uzunlukta olmalı
            truncating = 'pre' #truncating işlemi cümlenin başından veya sonundan pre ve post durumuna göre token atar.
        else:
            truncating = 'post' #cümlenin başı sonundan daha önemli olduğundan gelen texti ters çeviriyoruz.
            
        self.num_tokens = [len(x) for x in self.tokens]
        self.max_tokens = np.mean(self.num_tokens) + 2 * np.std(self.num_tokens) #RNN e vereceğimiz vectörün boyutlarını belirliyoruz.
        #bu ortalama ve standart sapmayla optimum bir büyüklük belirliyoruz.
        self.max_tokens = int(self.max_tokens)
        
        self.tokens_padded = pad_sequences(self.tokens,  #gelen input textte sıfırdan oluşan padding ekleyip boyutları eşit hale getiriyoruz.
                                          maxlen = self.max_tokens,
                                          padding=padding,
                                          truncating = truncating)
        
    def token_to_word(self,token):#sayının kelime karşılığını döndürür
        word = ' ' if token == 0 else self.index_to_word[token]
        return word
    
    def tokens_to_string(self,tokens): #verilen tokenlardan cümle döndürür
        words = [self.index_to_word[token] for token in tokens if token != 0]
        text = ' '.join(words)
        return text
    
    def text_to_tokens(self,text,padding,reverse = False): #verilen texti tokenlara dönüştürür
        tokens = self.texts_to_sequences([text])
        tokens = np.array(tokens)
        
        if reverse:
            tokens = np.flip(tokens,axis=1)
            truncating = 'pre'
        else:
            truncating = 'post'
            
        tokens = pad_sequences(tokens,
                              maxlen=self.max_tokens,
                              padding=padding,
                              truncating = truncating)
        return tokens

In [0]:
tokenizer_src = TokenizerWrap(texts = data_src, #encodera verilecek 
                             padding = 'pre',
                             reverse = True,
                             num_words=None)

In [0]:
tokenizer_dest = TokenizerWrap(texts = data_dest,#decodere verilecek
                             padding = 'post',
                             reverse = False,
                             num_words=None)

In [0]:
tokens_src = tokenizer_src.tokens_padded
tokens_dest = tokenizer_dest.tokens_padded
print(tokens_src.shape)
print(tokens_dest.shape)

(214294, 1399)
(214294, 171)

In [0]:
tokens_dest[0]

array([    7,    53,  1252,   592,    10,     1,   256,   128,    21,
          26,  2776,     3,   103,     4,  4629,  3407,   104,   246,
        1886,    41,  1067,   592,    10,   202,  2175,  2398,  1706,
          19, 44098,     5,  2660,     3,   738,  5368,   766,     5,
        2141,   786,    19,   246,   404,     6,     1,   276,    11,
        1162,  1111,  1454,   334,    19, 10436,   230,     3,    21,
         334,    11, 10208,  1333,    61,    12,     1,  1267,   243,
           4,   987,  2369,     3,    21,     2,  1655,  2531,  3167,
        2711,    21,     4,  3623,     6,  3832,    29,   440,   888,
          14,  8685,  1207,    84,  1581,     8,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0],
      dtype=int32)

In [0]:
tokenizer_dest.tokens_to_string(tokens_dest[0])

'ssstarttoken keep related supplies in the same area make an effort to clean a dedicated workspace after every session place loose supplies in large clearly visible containers use clotheslines and clips to hang sketches photos and reference material use every inch of the room for storage especially vertical space use chalkboard paint to make space for drafting ideas right on the walls purchase a label maker to make your organization strategy semi permanent make a habit of throwing out old excess or useless stuff each month eeendtoken'

In [0]:
tokens_src[0]

array([ 0,  0,  0, ..., 15,  3, 14], dtype=int32)

In [0]:
tokenizer_src.tokens_to_string(tokens_src[0])

"it toss months six next the in it use will you chance little is there months six last the in it used not have you if here sentimental be not do sketch old an or paint right the find to junk through digging minutes 30 spending than fun more lot a is it but moment the at fun be not may it declutter to time aside set you if only but thing good a is this mess a making and experimenting things new making constantly are artists later for away it file or out it throw either project a of part or essential not is it if studio your of purge a do month a once art about think to mind your freeing labels the follow just can you things storing or for looking energy mental your of all spending of instead everything solve can maker label a with afternoon an but cleaning when uncertainty and items lost to leading effect opposite the has usually this frequently reorganizing by space your optimize to trying things of location the moving keep you when comes disorganization of lot a change needs your as chalk with them relabel to you allowing equipment storage or jars over paint areas smaller for it use even can you space or equipment extra requiring without planning and sketches ideas for space perfect a you gives chalkboard a into wall one turning materials and tools your all for space vital provide but utilized under most the often are room the of reaches upper the supplies used infrequently for especially either high up get to afraid be not do space art or studio your in room more get to way easy and cheap a is and friend best artist's an is shelving inspiration for down and up pin to need or regularly touch you ideas and papers handle to way good a also is this easy and cheap tape or tacks with ruin or cut to want not do you that papers essential hold to them use and ceiling the along or wall a across wires the up string simply etc pigment paint for bottles squirt restaurant plastic pencils pens hold to slot each in cups with racks wine door the of back the on racks shoe canvas include mentioned just those beyond ideas some haphazardly about strewn it leaving without sight in things keep can you drawers plastic clear cheap and vases glasses old jars using by sight of out tucked of instead visually supplies of track keep to desire a from comes clutter artist of lot a people visual as art make to want you time every business to down get you help will workspace organized an disorganized bit a is studio your of rest the if even tidying or work any do to having without immediately working start and day next the down sit can you that way a in workspace the leave to endeavor surfaces dirty down wipe and materials unnecessary or trash discard night each clean etc wheel pottery easel desk the around immediately area the keeping means just it studio entire the cleaning mean not does this way the of out tucked area supplies secondary or infrequent area work dedicated area reference and inspiration day every use you things the area supplies essential include ideas some area smaller much a to search your limiting easier them finding make to supplies your for areas and groups broader make etc ink the by be should supplies print canvas and cleaner brushes with kept be should paints studio or home your of quadrant same the in batteries and cords lens necessary the all keep photographer a are you if"

In [0]:
token_start = tokenizer_dest.word_index[mark_start.strip()]
token_start

7

In [0]:
token_end = tokenizer_dest.word_index[mark_end.strip()]
token_end

8

In [0]:
encoder_input_data = tokens_src

In [0]:
decoder_input_data = tokens_dest[:,:-1] #sondan bir önceki tokena kadar verileri al
decoder_output_data = tokens_dest[:,1:] #1den sona kadar inputun 1 kaydırılmış hali

In [0]:
encoder_input_data[100]

array([ 0,  0,  0, ..., 16, 17, 11], dtype=int32)

In [0]:
decoder_input_data[100]

array([    7,    27,     4,   118,  4291,    46,    14,   911,  2733,
        1913,   955,     6,    62,  1521,    41,     2,  2370,  2296,
          10,     1,   886,   128,    19,     4,   484,     3,  4813,
           2,  2370,  2296,     3,    15,   544,    85,     5,   112,
          18,     1,  2370,  2296,    38,    56,     3,    43,   102,
          12,   288,   219,  4400,   283,   261,  4867,     2,  2370,
        2296,    40,    99,    21,     4,   511,   460,   102,     1,
         955,   283, 17707,     4,   172,  1062,    37,     1,  4291,
          46,   203,  1625,     8,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0],
      dtype=int32)

In [0]:
decoder_output_data[100]

array([   27,     4,   118,  4291,    46,    14,   911,  2733,  1913,
         955,     6,    62,  1521,    41,     2,  2370,  2296,    10,
           1,   886,   128,    19,     4,   484,     3,  4813,     2,
        2370,  2296,     3,    15,   544,    85,     5,   112,    18,
           1,  2370,  2296,    38,    56,     3,    43,   102,    12,
         288,   219,  4400,   283,   261,  4867,     2,  2370,  2296,
          40,    99,    21,     4,   511,   460,   102,     1,   955,
         283, 17707,     4,   172,  1062,    37,     1,  4291,    46,
         203,  1625,     8,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0],
      dtype=int32)

In [0]:
tokenizer_dest.tokens_to_string(decoder_input_data[100])

'ssstarttoken get a small garbage can or round cylinder shaped object of some sort place your guinea pig in the general area use a treat to lure your guinea pig to it stand back and see if the guinea pig will try to go around on its own eventually begin only treating your guinea pig when they make a full circle around the object begin enforcing a hand motion take the garbage can away gradually eeendtoken'

In [0]:
tokenizer_dest.tokens_to_string(decoder_output_data[100])

'get a small garbage can or round cylinder shaped object of some sort place your guinea pig in the general area use a treat to lure your guinea pig to it stand back and see if the guinea pig will try to go around on its own eventually begin only treating your guinea pig when they make a full circle around the object begin enforcing a hand motion take the garbage can away gradually eeendtoken'

In [0]:
num_encoder_words = len(tokenizer_src.word_index) + 1
num_decoder_words = len(tokenizer_dest.word_index) + 1

In [0]:
num_encoder_words

192102

In [0]:
num_decoder_words

89296

In [0]:
embedding_size = 100 #glove vektörlerinin uzunluğuyla aynı olmalı

In [0]:
word2vec = {} #eğitilmiş kelime glove kelime haznesini okuyoruz. Kelime anlamlarını tutuyor.
with open('glove.6B.100d.txt',encoding = 'UTF-8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vec = np.array(values[1:], dtype='float32')
        word2vec[word] = vec

In [0]:
embedding_matrix = np.random.uniform(-1, 1, (num_encoder_words, embedding_size)) #önce boş bir matrix oluştur
for word,i in tokenizer_src.word_index.items():#kaynak textteki kelimeler glovedan gelen kelimeler içinde yoksa glovedan kelime alıyoruz.
    if i < num_encoder_words:
        embedding_vector = word2vec.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [0]:
embedding_matrix.shape

(192102, 100)

In [0]:
encoder_input = Input(shape=(None,),name='encoder_input')

In [0]:
encoder_embedding = Embedding(input_dim=num_encoder_words,
                             output_dim=embedding_size,
                             weights = [embedding_matrix],
                             trainable=True,
                             name='encoder_embedding')

In [0]:
state_size = 256

In [0]:
encoder_gru1 = CuDNNGRU(state_size,name="encoder_gru1",return_sequences=True)
encoder_gru2 = CuDNNGRU(state_size,name="encoder_gru2",return_sequences=True)
encoder_gru3 = CuDNNGRU(state_size,name="encoder_gru3",return_sequences=False)

In [0]:
def connect_encoder():
    layer = encoder_input
    layer = encoder_embedding(layer)
    layer = encoder_gru1(layer)
    layer = encoder_gru2(layer)
    layer = encoder_gru3(layer)
    
    encoder_output = layer
    
    return encoder_output

In [0]:
encoder_output = connect_encoder()

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

In [0]:
decoder_initial_state = Input(shape = (state_size,),name='decoder_initial_state')

In [0]:
decoder_input = Input(shape=(None,),name='decoder_input')

In [0]:
decoder_embedding = Embedding(input_dim = num_decoder_words,
                             output_dim = embedding_size,
                             name = 'decoder_embedding')

In [0]:
decoder_gru1 = CuDNNGRU(state_size, name='decoder_gru1',return_sequences=True)
decoder_gru2 = CuDNNGRU(state_size, name='decoder_gru2',return_sequences=True)
decoder_gru3 = CuDNNGRU(state_size, name='decoder_gru3',return_sequences=True)

In [0]:
decoder_dense = Dense(num_decoder_words,
                     activation='linear',
                     name='decoder_output')

In [0]:
def connect_decoder(initial_state):
    layer = decoder_input
    layer = decoder_embedding(layer)
    layer = decoder_gru1(layer,initial_state = initial_state)
    layer = decoder_gru2(layer,initial_state = initial_state)
    layer = decoder_gru3(layer,initial_state = initial_state)
    
    decoder_output = decoder_dense(layer)
    
    return decoder_output

In [0]:
decoder_output = connect_decoder(initial_state=encoder_output)

In [0]:
model_train = Model(inputs=[encoder_input,decoder_input],outputs=[decoder_output])

In [0]:
model_encoder = Model(inputs=[encoder_input],outputs=[encoder_output])

In [0]:
decoder_output = connect_decoder(initial_state = decoder_initial_state)

In [0]:
model_decoder = Model(inputs=[decoder_input,decoder_initial_state],outputs=[decoder_output])

In [0]:
def sparse_cross_entropy(y_true,y_pred):
    loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y_true,logits=y_pred)
    loss_mean = tf.reduce_mean(loss)
    return loss_mean

In [0]:
optimizer = RMSprop(lr=1e-3)

In [0]:
decoder_target = tf.placeholder(dtype='int32',shape=(None,None))

In [0]:
model_train.compile(optimizer=optimizer,
                   loss=sparse_cross_entropy,
                   target_tensors=[decoder_target])

In [0]:
path_checkpoint = 'checkpoint.keras'
checkpoint = ModelCheckpoint(filepath=path_checkpoint,save_weights_only=True)

In [0]:
# create on Colab directory
model_train.save('model_more.h5')    
model_file = drive.CreateFile({'title' : 'model_more.h5'})
model_file.SetContentFile('model_more.h5')
model_file.Upload()

# download to google drive
drive.CreateFile({'id': model_file.get('id')})

model_train.save_weights('model_weights_more.h5')
weights_file = drive.CreateFile({'title' : 'model_weights_more.h5'})
weights_file.SetContentFile('model_weights_more.h5')
weights_file.Upload()
drive.CreateFile({'id': weights_file.get('id')})

GoogleDriveFile({'id': '1NJF4LUkimQgUnW1AcL6NdJMAZT1NEdS-'})

In [0]:



try:
  #  model_train.load_weights(path_checkpoint)
  # 3. reload weights from google drive into the model

  # use (get shareable link) to get file id
  last_weight_file = drive.CreateFile({'id': '1waobEqSnb2A5Cd0T_l5yC9Uo2Cwd6tNC'}) 
  last_weight_file.GetContentFile('last_weights_more.mat')
  model_train.load_weights('last_weights_more.mat')
except Exception as error:
    print('checkpoint yüklenemedi. eğitime baştan başlanıyor')
    print(error)

checkpoint yüklenemedi. eğitime baştan başlanıyor
Shapes (89296, 100) and (35609, 100) are incompatible

In [0]:
x_data = {'encoder_input': encoder_input_data,'decoder_input': decoder_input_data}

In [0]:
y_data = {'decoder_output': decoder_output_data}

In [0]:
model_train.fit(x=x_data,
               y=y_data,
               batch_size=64,
               epochs=1,
               callbacks=[checkpoint])
model_train.save('model_more.h5')

214294/214294 [==============================] - 3875s 18ms/sample - loss: 1.5581

In [0]:
def CalculateRougeScores(refrence_summary,model_summary,scoring = False):
    rouge = RougeCalculator(stopwords=True, lang="en")
    rouge_1 = rouge.rouge_n(
            summary=model_summary,
            references=refrence_summary,
            n=1)
    rouge_2 = rouge.rouge_n(
            summary=model_summary,
            references=[refrence_summary],
            n=2)
    rouge_L = rouge.rouge_l(
            summary=model_summary,
            references=[refrence_summary])
    if (scoring == False):
        print("ROUGE-1: {}, ROUGE-2: {}, ROUGE-L: {}".format(
            rouge_1, rouge_2, rouge_L
        ).replace(", ", "\n"))
    
    return rouge_1,rouge_2,rouge_L

In [0]:
def CalculateBleuScores(refrence_summary,model_summary,scoring = False):
    refrence_summary_list = []
    rs =nltk.word_tokenize(refrence_summary)
    #print(r)
    refrence_summary_list.append(rs)
#     print(refrence_summary_list)
    model_summary = nltk.word_tokenize(model_summary)

#     print(model_summary)
#     a = [['good', 'quality', 'dog', 'food']]
#     b = ['a', 'good', 'dog', 'food']
    
    score = sentence_bleu(refrence_summary_list, model_summary,weights=(1, 0, 0, 0))
    if(scoring == False):
        print("BLEU Score: {} ".format(
            score,).replace(", ", "\n"))
        
    return score

In [0]:
def summarize(input_text, true_output_text=None,scoring = False):
    input_tokens = tokenizer_src.text_to_tokens(text=input_text,
                                                reverse=True,
                                                padding='pre')
    
    initial_state = model_encoder.predict(input_tokens)  
    max_tokens = tokenizer_dest.max_tokens    
    decoder_input_data = np.zeros(shape=(1, max_tokens), dtype=np.int)
    
        
    token_int = token_start
    output_text = ''
    count_tokens = 0
    
    while token_int != token_end and count_tokens < max_tokens:
        decoder_input_data[0, count_tokens] = token_int
        x_data = {'decoder_initial_state': initial_state, 'decoder_input': decoder_input_data}
        
        decoder_output = model_decoder.predict(x_data)
        
        token_onehot = decoder_output[0, count_tokens, :]
        token_int = np.argmax(token_onehot)
        
        sampled_word = tokenizer_dest.token_to_word(token_int)
        output_text += ' ' + sampled_word
        count_tokens += 1
        
    
       
    
    if scoring == False:
        print('Input text:')
        print(input_text)
        print()

        print('AI Summarized text:')
        print(output_text)
        print()
        if true_output_text is not None:
            print('Human Summarized text')
            print(true_output_text)
            print()
            
        rouge_1,rouge_2,rouge_L = CalculateRougeScores(true_output_text,output_text)
        score = CalculateBleuScores(true_output_text,output_text)
    else:
        rouge_1,rouge_2,rouge_L = CalculateRougeScores(true_output_text,output_text,True)
        score = CalculateBleuScores(true_output_text,output_text,True)  
    
    return rouge_1,rouge_2,rouge_L,score
    print()
    print()
    print()

In [0]:
def Scoring():    
    #pbar = ProgressBar()
    rouge_1_news = 0
    rouge_2_news = 0
    rouge_L_news = 0
    bleu_news = 0
    
    
    for i in range(1,500):
        print(i)
        rouge_1,rouge_2,rouge_L,bleu = summarize(clean_texts[i],clean_summaries[i],True)
        rouge_1_news = rouge_1_news + rouge_1
        rouge_2_news = rouge_2_news + rouge_2
        rouge_L_news = rouge_L_news + rouge_L
        bleu_news = bleu_news + bleu              
    
    rouge_1_news_avg_score = rouge_1_news / i
    rouge_2_news_avg_score = rouge_2_news / i
    rouge_L_news_avg_score = rouge_L_news / i
    bleu_news_avg_score = bleu_news / i
    
    
    print("rouge_1_news: {}, rouge_2_news: {}, rouge_L_news: {}, bleu_news: {}".
          format(rouge_1_news_avg_score,rouge_2_news_avg_score,rouge_L_news_avg_score,bleu_news_avg_score).replace(", ", "\n"))

In [1]:
summarize(input_text=data_src[60], true_output_text=data_dest[60])

NameError: ignored

In [0]:
Scoring()

1

/usr/local/lib/python3.6/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 2-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

2

/usr/local/lib/python3.6/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 3-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

3
4

/usr/local/lib/python3.6/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 4-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
rouge_1_news: 0.06064800882952949
rouge_2_news: 0.007429197941610768
rouge_L_news: 0.05626409174239283
bleu_news: 0.07998710712924822